
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asbulwugirsilatfuscv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzYnVsd3VnaXJzaWxhdGZ1c2N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTMyMDksImV4cCI6MjA2MzI2OTIwOX0._DBBQp49EXXNbz9eFN24yVmQQBtyYY01pcgpJazS2_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
